development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: stock_management
  pool: 5
  username: root
  password: maheshwari

# development:
# 	adapter: postgresql
# 	encoding: unicode
# 	database: stock_management
# 	pool: 5
# 	username: postgres
# 	password: vaio